# Optimize test profile for faster compilation
[profile.test]
codegen-units = 256
debug = "line-tables-only"
split-debuginfo = "unpacked"
lto = "off"

# Optimize dev profile for faster compilation of project code,
# while dependencies are optimized for speed.
[profile.dev]
codegen-units = 256
debug = "line-tables-only"
split-debuginfo = "unpacked"
lto = "off"

[profile.dev.package."*"]
opt-level = 3

[doc]
all-features = true
